
import { Donation, UserProfile } from './types';
import { Timestamp } from 'firebase/firestore';

export const mockUsers: UserProfile[] = [
  {
    id: '1',
    displayName: 'Priya Krishnan',
    email: 'priya@example.com',
    photoURL: 'https://picsum.photos/seed/user1/100/100',
    points: 1250,
    address: '123 Anna Salai, Chennai',
    phone: '9840012345',
    role: 'donor',
  },
  {
    id: '2',
    displayName: 'Arun Kumar',
    email: 'arun@example.com',
    photoURL: 'https://picsum.photos/seed/user2/100/100',
    points: 200,
    address: '456 Natesan Nagar, Madurai',
    phone: '9841123456',
    role: 'receiver',
  },
  {
    id: '3',
    displayName: 'Sanjay Gupta',
    email: 'sanjay@example.com',
    photoURL: 'https://picsum.photos/seed/user3/100/100',
    points: 850,
    address: '789 Bharathi St, Coimbatore',
    phone: '9842234567',
    role: 'volunteer',
  },
  {
    id: '4',
    displayName: 'Meena Kumari',
    email: 'meena@example.com',
    photoURL: 'https://picsum.photos/seed/user4/100/100',
    points: 1500,
    address: '101 Gandhi Road, Trichy',
    phone: '9843345678',
    role: 'donor',
  },
  {
    id: '5',
    displayName: 'Karthik Raja',
    email: 'karthik@example.com',
    photoURL: 'https://picsum.photos/seed/user5/100/100',
    points: 1100,
    address: '212 VOC Street, Salem',
    phone: '9844456789',
    role: 'volunteer',
  },
];

export const mockDonations: Donation[] = [
  {
    id: 'd1',
    foodName: 'Sambar Rice',
    status: 'Available',
    quantity: '10 packets',
    location: 'Saravana Bhavan, T. Nagar',
    pickupBy: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '1',
      name: 'Priya Krishnan',
      email: 'priya@example.com',
      photoURL: 'https://picsum.photos/seed/user1/100/100',
      phone: '9840012345',
    },
    donorId: '1',
    lat: 13.047,
    lng: 80.237,
  },
  {
    id: 'd2',
    foodName: 'Idli Vada',
    status: 'Claimed',
    quantity: '20 sets',
    location: 'Murugan Idli Shop, Madurai',
    pickupBy: Timestamp.fromDate(new Date(Date.now() + 1 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '4',
      name: 'Meena Kumari',
      email: 'meena@example.com',
      photoURL: 'https://picsum.photos/seed/user4/100/100',
      phone: '9843345678',
    },
    donorId: '4',
    lat: 9.919,
    lng: 78.116,
  },
  {
    id: 'd3',
    foodName: 'Canned Goods',
    status: 'Available',
    quantity: '25 cans',
    location: 'Reliance Mart, R.S. Puram',
    pickupBy: Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '1',
      name: 'Priya Krishnan',
      email: 'priya@example.com',
      photoURL: 'https://picsum.photos/seed/user1/100/100',
      phone: '9840012345',
    },
    donorId: '1',
    lat: 11.005,
    lng: 76.95,
  },
   {
    id: 'd4',
    foodName: 'Fresh Vegetables',
    status: 'Delivered',
    quantity: '5 kg',
    location: 'Uzhavar Sandhai, Trichy',
    pickupBy: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '4',
      name: 'Meena Kumari',
      email: 'meena@example.com',
      photoURL: 'https://picsum.photos/seed/user4/100/100',
      phone: '9843345678',
    },
    donorId: '4',
    lat: 10.790,
    lng: 78.704,
  },
];
