import { UserProfile } from './types';

export const mockUsers: UserProfile[] = [
  {
    id: 'student-1',
    displayName: 'Priya Krishnan',
    email: 'priya@example.com',
    photoURL: 'https://picsum.photos/seed/user1/100/100',
    loyaltyPoints: 1250,
    address: 'Central Hostel Wing, Block A',
    phone: '+91 98400 12345',
    role: 'student',
    canteenId: 'canteen-central',
    counterId: null,
    favorites: [],
    notificationPreferences: {
      pushReady: true,
      emailUpdates: true,
    },
    verified: true,
  },
  {
    id: 'student-2',
    displayName: 'Arun Kumar',
    email: 'arun@example.com',
    photoURL: 'https://picsum.photos/seed/user2/100/100',
    loyaltyPoints: 980,
    address: 'Innovation Hostel, Block C',
    phone: '+91 98411 23456',
    role: 'student',
    canteenId: 'canteen-tech-park',
    counterId: null,
    favorites: [],
    notificationPreferences: {
      pushReady: true,
      emailUpdates: false,
    },
    verified: true,
  },
  {
    id: 'student-3',
    displayName: 'Meera Dsouza',
    email: 'meera@example.com',
    photoURL: 'https://picsum.photos/seed/user3/100/100',
    loyaltyPoints: 1430,
    address: 'Health Sciences Hostel, Level 3',
    phone: '+91 98422 34567',
    role: 'student',
    canteenId: 'canteen-health',
    counterId: null,
    favorites: [],
    notificationPreferences: {
      pushReady: true,
      emailUpdates: true,
    },
    verified: true,
  },
  {
    id: 'student-4',
    displayName: 'Sanjay Gupta',
    email: 'sanjay@example.com',
    photoURL: 'https://picsum.photos/seed/user4/100/100',
    loyaltyPoints: 870,
    address: 'Day Scholar Apartments, Tower 5',
    phone: '+91 98433 45678',
    role: 'student',
    canteenId: 'canteen-central',
    counterId: null,
    favorites: [],
    notificationPreferences: {
      pushReady: false,
      emailUpdates: true,
    },
    verified: false,
  },
  {
    id: 'student-5',
    displayName: 'Lakshmi Rao',
    email: 'lakshmi@example.com',
    photoURL: 'https://picsum.photos/seed/user5/100/100',
    loyaltyPoints: 1010,
    address: 'Tech Park Residences, Tower 2',
    phone: '+91 98444 56789',
    role: 'student',
    canteenId: 'canteen-tech-park',
    counterId: null,
    favorites: [],
    notificationPreferences: {
      pushReady: true,
      emailUpdates: false,
    },
    verified: true,
  },
];
