import { Donation, UserProfile } from './types';
import { Timestamp } from 'firebase/firestore';

export const mockUsers: UserProfile[] = [
  {
    id: '1',
    displayName: 'Alice Donor',
    email: 'alice@example.com',
    photoURL: 'https://picsum.photos/seed/user1/100/100',
    points: 1250,
    address: '123 Main St, Anytown, USA',
    phone: '555-1234',
    role: 'donor',
  },
  {
    id: '2',
    displayName: 'Bob Receiver',
    email: 'bob@example.com',
    photoURL: 'https://picsum.photos/seed/user2/100/100',
    points: 200,
    address: '456 Oak Ave, Anytown, USA',
    phone: '555-5678',
    role: 'receiver',
  },
  {
    id: '3',
    displayName: 'Charlie Volunteer',
    email: 'charlie@example.com',
    photoURL: 'https://picsum.photos/seed/user3/100/100',
    points: 850,
    address: '789 Pine Ln, Anytown, USA',
    phone: '555-9012',
    role: 'volunteer',
  },
  {
    id: '4',
    displayName: 'Diana Donor',
    email: 'diana@example.com',
    photoURL: 'https://picsum.photos/seed/user4/100/100',
    points: 1500,
    address: '101 Maple Dr, Anytown, USA',
    phone: '555-3456',
    role: 'donor',
  },
  {
    id: '5',
    displayName: 'Ethan Volunteer',
    email: 'ethan@example.com',
    photoURL: 'https://picsum.photos/seed/user5/100/100',
    points: 1100,
    address: '212 Birch Rd, Anytown, USA',
    phone: '555-7890',
    role: 'volunteer',
  },
];

export const mockDonations: Donation[] = [
  {
    id: 'd1',
    foodName: 'Fresh Loaf of Bread',
    status: 'Available',
    quantity: '10 loaves',
    location: 'Downtown Bakery, 123 Main St',
    pickupBy: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '1',
      name: 'Alice Donor',
      email: 'alice@example.com',
      photoURL: 'https://picsum.photos/seed/user1/100/100',
      phone: '555-1234',
    },
    donorId: '1',
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: 'd2',
    foodName: 'Homemade Vegetable Soup',
    status: 'Claimed',
    quantity: '5 liters',
    location: 'Community Kitchen, 456 Oak Ave',
    pickupBy: Timestamp.fromDate(new Date(Date.now() + 1 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '4',
      name: 'Diana Donor',
      email: 'diana@example.com',
      photoURL: 'https://picsum.photos/seed/user4/100/100',
      phone: '555-3456',
    },
    donorId: '4',
    lat: 34.055,
    lng: -118.25,
  },
  {
    id: 'd3',
    foodName: 'Canned Beans and Corn',
    status: 'Available',
    quantity: '25 cans',
    location: 'Pantry Hub, 789 Pine Ln',
    pickupBy: Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '1',
      name: 'Alice Donor',
      email: 'alice@example.com',
      photoURL: 'https://picsum.photos/seed/user1/100/100',
      phone: '555-1234',
    },
    donorId: '1',
    lat: 34.05,
    lng: -118.24,
  },
   {
    id: 'd4',
    foodName: 'Fresh Apples',
    status: 'Delivered',
    quantity: '2 crates',
    location: 'Green Grocer, 101 Maple Dr',
    pickupBy: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    donor: {
      id: '4',
      name: 'Diana Donor',
      email: 'diana@example.com',
      photoURL: 'https://picsum.photos/seed/user4/100/100',
      phone: '555-3456',
    },
    donorId: '4',
    lat: 34.04,
    lng: -118.23,
  },
];
