import { Canteen, Coupon, MenuItem, OfferBanner } from './types';

export const defaultCanteens: Canteen[] = [
  {
    id: 'canteen-central',
    name: 'Central Campus Canteen',
    location: 'Main Quadrangle, Level 1',
    description:
      'The primary dining hub of the campus serving freshly cooked meals across breakfast, lunch, and dinner.',
    counters: [
      { id: 'central-counter-1', name: 'Main Kitchen' },
      { id: 'central-counter-2', name: 'Quick Bites' },
      { id: 'central-counter-3', name: 'Beverage Bar' },
    ],
    isActive: true,
    totalRevenue: 215400,
    totalOrders: 1842,
  },
  {
    id: 'canteen-tech-park',
    name: 'Tech Park Food Court',
    location: 'Innovation Block, Level 2',
    description:
      'Fast casual dining with an emphasis on grab-and-go meals designed for busy schedules.',
    counters: [
      { id: 'tech-counter-1', name: 'Express Meals' },
      { id: 'tech-counter-2', name: 'Salad & Bowls' },
      { id: 'tech-counter-3', name: 'Coffee Studio' },
    ],
    isActive: true,
    totalRevenue: 138750,
    totalOrders: 1260,
  },
  {
    id: 'canteen-health',
    name: 'Wellness Canteen',
    location: 'Health Sciences Wing',
    description:
      'Balanced, nutritious options curated with our nutrition team for mindful eating.',
    counters: [
      { id: 'health-counter-1', name: 'Fresh Bowls' },
      { id: 'health-counter-2', name: 'Artisan Sandwiches' },
      { id: 'health-counter-3', name: 'Hydration Station' },
    ],
    isActive: true,
    totalRevenue: 96520,
    totalOrders: 872,
  },
];

export const defaultMenuItems: MenuItem[] = [
  {
    id: 'item-masala-dosa',
    canteenId: 'canteen-central',
    counterId: 'central-counter-1',
    name: 'Masala Dosa Combo',
    category: 'Breakfast',
    foodType: 'Veg',
    price: 65,
    imageUrl: 'https://images.unsplash.com/photo-1626536628654-66f16e75fb4b?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Fermented batter', 'Potato masala', 'Chutneys', 'Sambar'],
    description: 'Crisp dosa served with a hearty potato masala, sambar, and twin chutneys.',
    isAvailable: true,
    rating: 4.8,
    ratingCount: 542,
    tags: ['Popular', 'South Indian'],
  },
  {
    id: 'item-idli-vada',
    canteenId: 'canteen-central',
    counterId: 'central-counter-1',
    name: 'Idli Vada Platter',
    category: 'Breakfast',
    foodType: 'Veg',
    price: 55,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Steamed rice cakes', 'Lentil doughnuts', 'Sambar', 'Chutney'],
    description: 'Soft idlis and crispy vadas served with piping hot sambar and coconut chutney.',
    isAvailable: true,
    rating: 4.6,
    ratingCount: 328,
    tags: ['Light', 'Campus Favorite'],
  },
  {
    id: 'item-paneer-wrap',
    canteenId: 'canteen-tech-park',
    counterId: 'tech-counter-1',
    name: 'Grilled Paneer Wrap',
    category: 'Lunch',
    foodType: 'Veg',
    price: 95,
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Whole wheat wrap', 'Smoked paneer', 'Bell peppers', 'Mint yogurt'],
    description: 'High-protein wrap filled with charred paneer, crunchy veggies, and herbed yogurt.',
    isAvailable: true,
    rating: 4.5,
    ratingCount: 210,
    tags: ['High Protein', 'Grab & Go'],
  },
  {
    id: 'item-chicken-rice-bowl',
    canteenId: 'canteen-tech-park',
    counterId: 'tech-counter-1',
    name: 'Teriyaki Chicken Rice Bowl',
    category: 'Lunch',
    foodType: 'Non-Veg',
    price: 125,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Steamed rice', 'Grilled chicken', 'Teriyaki glaze', 'Sesame greens'],
    description: 'Japanese-style bowl with glazed chicken, stir-fried greens, and sticky jasmine rice.',
    isAvailable: true,
    rating: 4.7,
    ratingCount: 178,
    tags: ['Signature', 'Protein Rich'],
  },
  {
    id: 'item-millet-salad',
    canteenId: 'canteen-health',
    counterId: 'health-counter-1',
    name: 'Rainbow Millet Bowl',
    category: 'Lunch',
    foodType: 'Veg',
    price: 110,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Foxtail millet', 'Roasted vegetables', 'Pumpkin seeds', 'Lemon dressing'],
    description: 'A wholesome bowl packed with micronutrients, fiber, and plant protein.',
    isAvailable: true,
    rating: 4.4,
    ratingCount: 142,
    tags: ['Gluten Free', 'Dietician Approved'],
  },
  {
    id: 'item-filter-coffee',
    canteenId: 'canteen-central',
    counterId: 'central-counter-3',
    name: 'Madras Filter Coffee',
    category: 'Beverages',
    foodType: 'Veg',
    price: 30,
    imageUrl: 'https://images.unsplash.com/photo-1527169402691-feff5539e52c?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Filter coffee decoction', 'Frothed milk', 'Jaggery'],
    description: 'Traditional brass-filter brewed coffee finished with jaggery-infused milk.',
    isAvailable: true,
    rating: 4.9,
    ratingCount: 689,
    tags: ['Beverage', 'Energy Boost'],
  },
  {
    id: 'item-berry-smoothie',
    canteenId: 'canteen-health',
    counterId: 'health-counter-3',
    name: 'Antioxidant Berry Smoothie',
    category: 'Beverages',
    foodType: 'Veg',
    price: 90,
    imageUrl: 'https://images.unsplash.com/photo-1542444459-db63adcb1f85?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Blueberries', 'Greek yogurt', 'Flax seeds', 'Honey'],
    description: 'Creamy smoothie packed with antioxidants and omega-rich seeds.',
    isAvailable: true,
    rating: 4.3,
    ratingCount: 96,
    tags: ['Cold', 'Immunity'],
  },
  {
    id: 'item-paneer-tikka-sandwich',
    canteenId: 'canteen-tech-park',
    counterId: 'tech-counter-2',
    name: 'Paneer Tikka Multigrain Sandwich',
    category: 'Snacks',
    foodType: 'Veg',
    price: 85,
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Multigrain bread', 'Smoked paneer', 'Herbed mayo'],
    description: 'Toasted multigrain sandwich loaded with smoky paneer and crunchy veggies.',
    isAvailable: true,
    rating: 4.5,
    ratingCount: 201,
    tags: ['Toasted', 'Evening Snack'],
  },
  {
    id: 'item-egg-kathi-roll',
    canteenId: 'canteen-central',
    counterId: 'central-counter-2',
    name: 'Double Egg Kathi Roll',
    category: 'Snacks',
    foodType: 'Non-Veg',
    price: 75,
    imageUrl: 'https://images.unsplash.com/photo-1612874471380-27b5bfa32f29?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Parotta', 'Spiced eggs', 'Onion slaw', 'Mint chutney'],
    description: 'Street-style flaky parotta wrap stuffed with masala eggs and crunchy onion slaw.',
    isAvailable: true,
    rating: 4.6,
    ratingCount: 256,
    tags: ['Protein', 'Quick Bites'],
  },
  {
    id: 'item-south-indian-thali',
    canteenId: 'canteen-central',
    counterId: 'central-counter-1',
    name: 'South Indian Mini Thali',
    category: 'Lunch',
    foodType: 'Veg',
    price: 130,
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Rice', 'Sambar', 'Poriyal', 'Rasam', 'Curd'],
    description: 'Campus-favourite thali with rotating vegetables and desserts.',
    isAvailable: true,
    rating: 4.7,
    ratingCount: 412,
    tags: ['Combo', 'Comfort Food'],
  },
  {
    id: 'item-nutty-energy-bar',
    canteenId: 'canteen-health',
    counterId: 'health-counter-2',
    name: 'Nutty Energy Bar',
    category: 'Snacks',
    foodType: 'Veg',
    price: 45,
    imageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Oats', 'Dates', 'Almonds', 'Chia seeds'],
    description: 'Handcrafted bar that keeps you energised between lectures.',
    isAvailable: true,
    rating: 4.2,
    ratingCount: 88,
    tags: ['Healthy', 'Vegan Friendly'],
  },
];

export const defaultCoupons: Coupon[] = [
  {
    code: 'FIRST10',
    description: 'Get 10% off on your first order.',
    discountType: 'percentage',
    value: 10,
    isActive: true,
    maxDiscountAmount: 75,
  },
  {
    code: 'TEABREAK',
    description: 'Flat ₹15 off on beverages above ₹150.',
    discountType: 'flat',
    value: 15,
    isActive: true,
    minOrderValue: 150,
  },
  {
    code: 'FITMEAL',
    description: '12% off on wellness canteen combos every Wednesday.',
    discountType: 'percentage',
    value: 12,
    isActive: true,
    minOrderValue: 200,
    maxDiscountAmount: 60,
  },
];

export const defaultOfferBanners: OfferBanner[] = [
  {
    id: 'banner-breakfast',
    title: 'Breakfast Combos at ₹79',
    description: 'Kickstart your mornings with hearty South Indian staples.',
    imageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1200&q=80',
    ctaText: 'Order Breakfast',
    couponCode: 'FIRST10',
    highlightColor: 'from-orange-400 via-amber-300 to-yellow-400',
  },
  {
    id: 'banner-wellness',
    title: 'Wellness Wednesdays',
    description: 'Pick any nutritionist-approved bowl and earn double points.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    ctaText: 'Explore Healthy Bowls',
    couponCode: 'FITMEAL',
    highlightColor: 'from-emerald-400 via-green-300 to-lime-300',
  },
  {
    id: 'banner-beverages',
    title: 'Evening Beverage Fest',
    description: 'Cafe classics, iced teas & smoothies at happy hour pricing.',
    imageUrl: 'https://images.unsplash.com/photo-1527169402691-feff5539e52c?auto=format&fit=crop&w=1200&q=80',
    ctaText: 'Sip & Save',
    couponCode: 'TEABREAK',
    highlightColor: 'from-sky-400 via-blue-300 to-purple-300',
  },
];
